FROM bitwalker/alpine-erlang:latest

# Set environment variables
ENV MIX_ENV=prod

# Copy tarball release
ADD _build/prod/rel/badges/releases/0.5.0/badges.tar.gz ./

# Set user
USER default

# Set entrypoint
ENTRYPOINT ["./bin/badges"]
